import { NextResponse } from 'next/server'

// ─── Mock Data ────────────────────────────────────────────────

const insightCards = [
  {
    id: 'efficiency',
    title: 'Meeting Efficiency Score',
    icon: 'Gauge',
    primaryMetric: 87,
    primaryUnit: '/100',
    secondaryMetric: '+12% vs last quarter',
    trend: 'up' as const,
    color: '#10b981',
    details: 'Your meetings have improved significantly. The average meeting now achieves 87% of its stated objectives within the scheduled time, up from 75% last quarter. Key driver: improved pre-meeting agenda preparation.',
  },
  {
    id: 'utilization',
    title: 'Agent Utilization',
    icon: 'Users',
    primaryMetric: 94,
    primaryUnit: '%',
    secondaryMetric: 'Top: Dr. Chen (98%)',
    trend: 'up' as const,
    color: '#06b6d4',
    details: 'Agent participation is near-optimal. Dr. Sarah Chen leads with 98% engagement rate. Consider increasing Dr. Nakamura\'s involvement — currently at 72%, below the team average of 89%.',
    agents: [
      { name: 'Dr. Chen', pct: 98, color: '#10b981' },
      { name: 'Dr. Zhang', pct: 95, color: '#06b6d4' },
      { name: 'Dr. Wang', pct: 92, color: '#8b5cf6' },
      { name: 'Dr. Davis', pct: 88, color: '#f59e0b' },
      { name: 'Dr. Ross', pct: 85, color: '#ef4444' },
      { name: 'Dr. Nakamura', pct: 72, color: '#ec4899' },
    ],
  },
  {
    id: 'clustering',
    title: 'Topic Clustering',
    icon: 'Network',
    primaryMetric: 8,
    primaryUnit: ' clusters',
    secondaryMetric: '3 cross-project themes',
    trend: 'flat' as const,
    color: '#8b5cf6',
    details: 'Discussions cluster into 8 major topic groups. Three themes span multiple projects: "computational efficiency", "data quality", and "experimental validation". Consider cross-project working sessions.',
    clusters: [
      { name: 'Protein Folding', size: 42, x: 25, y: 30, color: '#10b981' },
      { name: 'Drug Screening', size: 35, x: 60, y: 20, color: '#06b6d4' },
      { name: 'Gene Editing', size: 28, x: 15, y: 65, color: '#8b5cf6' },
      { name: 'Biomarkers', size: 24, x: 75, y: 55, color: '#f59e0b' },
      { name: 'ML Models', size: 38, x: 45, y: 50, color: '#ef4444' },
      { name: 'Data Pipeline', size: 20, x: 85, y: 30, color: '#ec4899' },
      { name: 'Clinical Trial', size: 18, x: 50, y: 80, color: '#14b8a6' },
      { name: 'Validation', size: 22, x: 30, y: 75, color: '#a855f7' },
    ],
  },
  {
    id: 'decision',
    title: 'Decision Quality Index',
    icon: 'Target',
    primaryMetric: 82,
    primaryUnit: '/100',
    secondaryMetric: '18 unanimous, 4 voted',
    trend: 'up' as const,
    color: '#f59e0b',
    details: 'Decision quality has improved. 82% of decisions are fully implemented within 2 weeks. Unanimous decisions show 95% follow-through vs. 78% for voted decisions. The remaining gap is in resource allocation decisions.',
  },
  {
    id: 'action-items',
    title: 'Action Item Completion',
    icon: 'CheckCircle',
    primaryMetric: 76,
    primaryUnit: '%',
    secondaryMetric: '42 of 55 items completed',
    trend: 'up' as const,
    color: '#14b8a6',
    details: 'Action item completion rate is 76%, up from 68% last month. 13 items remain open — 5 are blocked by external dependencies, 4 are in progress, 3 are overdue. Focus on the CRISPR optimization experiment review.',
  },
  {
    id: 'velocity',
    title: 'Research Velocity',
    icon: 'TrendingUp',
    primaryMetric: 3.2,
    primaryUnit: 'x',
    secondaryMetric: 'Acceleration: +0.4x',
    trend: 'up' as const,
    color: '#ec4899',
    details: 'Research output velocity has increased to 3.2x baseline. This acceleration is driven by improved tool integration (AlphaFold, ESM) and streamlined meeting workflows. At current rate, Q2 targets are achievable 3 weeks ahead of schedule.',
  },
]

const trendData = {
  months: ['Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan'],
  series: [
    {
      name: 'Meeting Frequency',
      color: '#10b981',
      data: [18, 22, 25, 20, 28, 32, 16, 30, 24, 32, 18, 27],
    },
    {
      name: 'Discussion Depth',
      color: '#06b6d4',
      data: [65, 70, 72, 68, 78, 82, 60, 85, 80, 88, 75, 84],
    },
    {
      name: 'Decision Rate',
      color: '#8b5cf6',
      data: [45, 52, 58, 55, 62, 68, 50, 72, 70, 75, 65, 78],
    },
    {
      name: 'Innovation Score',
      color: '#f59e0b',
      data: [30, 35, 42, 38, 48, 52, 28, 55, 60, 65, 50, 68],
    },
  ],
}

const recommendations = [
  {
    id: 'r1',
    priority: 'high' as const,
    title: 'Restructure Weekly Standup Format',
    description: 'Current 60-minute standups show declining engagement after 25 minutes. Analysis suggests switching to a 30-minute async update + 20-minute focused discussion format would improve efficiency by an estimated 35%.',
    expectedImpact: '35% time savings, 20% higher engagement',
    effort: 'easy' as const,
    category: 'Scheduling',
  },
  {
    id: 'r2',
    priority: 'high' as const,
    title: 'Add Computational Chemist to Drug Discovery Meetings',
    description: 'Drug discovery discussions lack molecular dynamics expertise. Adding a computational chemist agent could reduce decision cycles by 40% based on pattern analysis from similar projects.',
    expectedImpact: '40% faster decision cycles on compound selection',
    effort: 'medium' as const,
    category: 'Agent Selection',
  },
  {
    id: 'r3',
    priority: 'medium' as const,
    title: 'Implement Structured Debate Protocol',
    description: 'Meetings with dissenting opinions produce 60% more innovative outcomes. Introduce a formal "Devil\'s Advocate" rotation to ensure critical evaluation of proposals.',
    expectedImpact: '60% increase in novel research directions',
    effort: 'easy' as const,
    category: 'Discussion Format',
  },
  {
    id: 'r4',
    priority: 'high' as const,
    title: 'Automated Follow-up Action Tracking',
    description: '24% of action items are forgotten by the next meeting. Implement automated reminders with escalation triggers at 3-day and 7-day intervals post-meeting.',
    expectedImpact: '90% action item awareness, 15% faster completion',
    effort: 'medium' as const,
    category: 'Follow-up',
  },
  {
    id: 'r5',
    priority: 'medium' as const,
    title: 'Schedule Cross-Project Knowledge Sync',
    description: 'Three recurring themes (computational efficiency, data quality, validation) span multiple projects. Monthly 45-minute cross-project syncs could eliminate redundant discussions.',
    expectedImpact: '25% reduction in repeated discussions',
    effort: 'easy' as const,
    category: 'Scheduling',
  },
  {
    id: 'r6',
    priority: 'low' as const,
    title: 'Explore Cryo-EM Integration Pipeline',
    description: 'Protein structure prediction meetings show growing interest in experimental validation through Cryo-EM. Allocating research time to this integration could unlock new publication opportunities.',
    expectedImpact: '2-3 potential high-impact publications',
    effort: 'hard' as const,
    category: 'Research Direction',
  },
  {
    id: 'r7',
    priority: 'medium' as const,
    title: 'Optimize Meeting Timing for Peak Performance',
    description: 'Analysis shows meetings between 10:00-11:30 AM produce 30% more concrete decisions. Consider shifting the weekly research review from 2:00 PM to 10:30 AM.',
    expectedImpact: '30% increase in decision quality',
    effort: 'easy' as const,
    category: 'Scheduling',
  },
  {
    id: 'r8',
    priority: 'low' as const,
    title: 'Create Molecular Dynamics Simulation Agent',
    description: 'Frequent references to simulation parameters suggest adding a specialized MD simulation agent would significantly enhance drug discovery and protein engineering discussions.',
    expectedImpact: 'Better-informed computational decisions',
    effort: 'hard' as const,
    category: 'Agent Selection',
  },
]

const sentimentAnalysis = {
  overall: { positive: 62, neutral: 28, negative: 10 },
  trendOverTime: [
    65, 60, 58, 62, 68, 72, 55, 70, 74, 76, 68, 73,
  ],
  wordSentiment: [
    { word: 'promising', score: 0.92 },
    { word: 'breakthrough', score: 0.95 },
    { word: 'efficient', score: 0.85 },
    { word: 'validated', score: 0.88 },
    { word: 'excellent', score: 0.94 },
    { word: 'optimized', score: 0.80 },
    { word: 'potential', score: 0.75 },
    { word: 'innovative', score: 0.82 },
    { word: 'robust', score: 0.78 },
    { word: 'successful', score: 0.90 },
    { word: 'interesting', score: 0.65 },
    { word: 'progress', score: 0.70 },
    { word: 'accurate', score: 0.76 },
    { word: 'significant', score: 0.72 },
    { word: 'collaboration', score: 0.68 },
    { word: 'neutral', score: 0.50 },
    { word: 'review', score: 0.52 },
    { word: 'update', score: 0.48 },
    { word: 'baseline', score: 0.45 },
    { word: 'preliminary', score: 0.42 },
    { word: 'iteration', score: 0.40 },
    { word: 'standard', score: 0.38 },
    { word: 'concern', score: 0.30 },
    { word: 'delay', score: -0.35 },
    { word: 'issue', score: -0.40 },
    { word: 'bottleneck', score: -0.55 },
    { word: 'unclear', score: -0.50 },
    { word: 'overdue', score: -0.65 },
    { word: 'risk', score: -0.45 },
    { word: 'problematic', score: -0.70 },
  ],
  positivePhrases: [
    'The binding affinity results exceeded our expectations',
    'Excellent progress on the CRISPR off-target prediction model',
    'The new pipeline reduced computation time by 40%',
  ],
  negativePhrases: [
    'The metagenomic platform migration is 3 weeks behind schedule',
    'Data quality issues in the RNA-seq samples need resolution',
    'Resource constraints limiting validation experiments',
  ],
}

const patternDetection = {
  recurringTopics: [
    { topic: 'Protein Structure', count: 47, weight: 1.0 },
    { topic: 'Drug Screening', count: 38, weight: 0.85 },
    { topic: 'ML Models', count: 35, weight: 0.82 },
    { topic: 'Gene Editing', count: 31, weight: 0.78 },
    { topic: 'Biomarker Discovery', count: 28, weight: 0.74 },
    { topic: 'Data Pipeline', count: 25, weight: 0.70 },
    { topic: 'Validation', count: 23, weight: 0.67 },
    { topic: 'Publication Strategy', count: 20, weight: 0.63 },
    { topic: 'Funding', count: 18, weight: 0.59 },
    { topic: 'Collaboration', count: 16, weight: 0.55 },
    { topic: 'Cryo-EM', count: 14, weight: 0.50 },
    { topic: 'Clinical Trial', count: 12, weight: 0.46 },
  ],
  agentInteractions: {
    agents: ['Chen', 'Zhang', 'Wang', 'Davis', 'Ross', 'Nakamura'],
    matrix: [
      [0, 12, 8, 6, 10, 4],
      [12, 0, 5, 9, 7, 3],
      [8, 5, 0, 4, 11, 6],
      [6, 9, 4, 0, 8, 7],
      [10, 7, 11, 8, 0, 5],
      [4, 3, 6, 7, 5, 0],
    ],
  },
  timePatterns: {
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    hours: ['9AM', '10AM', '11AM', '12PM', '1PM', '2PM', '3PM', '4PM', '5PM'],
    effectiveness: [
      [0.6, 0.85, 0.9, 0.5, 0.4, 0.7, 0.75, 0.6, 0.3],
      [0.7, 0.9, 0.95, 0.55, 0.45, 0.8, 0.7, 0.65, 0.35],
      [0.65, 0.88, 0.92, 0.6, 0.5, 0.75, 0.8, 0.7, 0.4],
      [0.55, 0.82, 0.88, 0.5, 0.45, 0.72, 0.78, 0.6, 0.3],
      [0.5, 0.78, 0.85, 0.45, 0.4, 0.65, 0.7, 0.55, 0.25],
    ],
  },
  decisions: {
    unanimous: 18,
    voted: 8,
    deferred: 5,
    total: 31,
  },
}

const insightHistory = [
  {
    id: 'h1',
    title: 'Q4 2024 Research Review Analysis',
    timestamp: '2025-01-15T14:30:00Z',
    summary: 'Comprehensive review of Q4 research meetings. Key finding: cross-project collaboration increased by 28%.',
  },
  {
    id: 'h2',
    title: 'December Efficiency Report',
    timestamp: '2024-12-31T10:00:00Z',
    summary: 'December showed a temporary dip in meeting efficiency (78%) due to holiday scheduling conflicts. Recovery trend observed.',
  },
  {
    id: 'h3',
    title: 'CRISPR Project Deep Dive',
    timestamp: '2024-12-15T16:45:00Z',
    summary: 'Focused analysis on CRISPR optimization meetings. Identified 3 key bottlenecks in guide RNA design workflow.',
  },
  {
    id: 'h4',
    title: 'Agent Performance Quarterly',
    timestamp: '2024-12-01T09:15:00Z',
    summary: 'All agents performing above baseline. Dr. Chen and Dr. Zhang identified as collaboration anchors.',
  },
  {
    id: 'h5',
    title: 'Innovation Index Assessment',
    timestamp: '2024-11-15T11:00:00Z',
    summary: 'Innovation score trending upward (+22% YoY). Structured debate format correlated with highest innovation outputs.',
  },
]

// ─── GET Handler ──────────────────────────────────────────────

export async function GET() {
  return NextResponse.json({
    insightCards,
    trendData,
    recommendations,
    sentimentAnalysis,
    patternDetection,
    insightHistory,
  })
}
